import PDFDocument from 'pdfkit';
import { Response } from 'express';

export const generateMedicalPDF = (
    res: Response, 
    patientName: string, 
    clinicalSummary: string, 
    stats: any
) => {
    const doc = new PDFDocument({ margin: 50 });

    // Pipe to response
    doc.pipe(res);

    // Header
    doc.fontSize(20).text('NeuroScan Clinical Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Patient: ${patientName}`);
    doc.text(`Date: ${new Date().toLocaleDateString()}`);
    doc.text(`Report ID: #${Math.floor(Math.random() * 100000)}`);
    doc.moveDown(2);

    // Clinical Summary Section
    doc.fontSize(16).text('AI-Generated Clinical Insights', { underline: true });
    doc.moveDown(0.5);
    doc.fontSize(11).text(clinicalSummary, {
        align: 'justify',
        lineGap: 4
    });
    doc.moveDown(2);

    // Statistics Section
    doc.fontSize(16).text('Key Metrics Overview', { underline: true });
    doc.moveDown(0.5);

    // Simple Table-like structure
    const metrics = [
        { label: 'Cognitive Stability Score', value: stats.cognitiveScore || 'N/A' },
        { label: 'Agitation Frequency (Weekly)', value: stats.agitationFreq || 'N/A' },
        { label: 'Average Sleep Duration', value: stats.avgSleep || 'N/A' },
        { label: 'Medication Adherence', value: stats.medAdherence || 'N/A' }
    ];

    metrics.forEach(m => {
        doc.fontSize(12).text(`${m.label}: `, { continued: true, bold: true })
           .text(m.value.toString(), { bold: false });
        doc.moveDown(0.3);
    });

    doc.moveDown(2);
    
    // Disclaimer
    doc.fontSize(8).fillColor('grey')
       .text('This report is generated by NeuroScan AI algorithms as a decision support tool. It does not replace professional medical diagnosis.', { align: 'center', valign: 'bottom' });

    doc.end();
};